base_url = "https://zolt.frazier.software"
default_language = "en"
hard_link_static = true

title = "zolt"
description = "An opinionated Zola skeleton for starting new sites faster."
author = "zolt"

compile_sass = true
minify_html = true
build_search_index = true

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [
    { name = "tags", paginate_by = 4, paginate_path = "" },
    { name = "series", feed = true },
    { name = "location", paginate_by = 4, paginate_path = "" },
]

[search]
include_date = true

[markdown]
lazy_async_image = true
insert_anchor_links = "right"
render_emoji = true
github_alerts = true
bottom_footnotes = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra.zolt]
version = "1.1.1"

[extra.social]
image = "img/og-default.png"
twitter = "@zolt"

[extra.contact]
turnstile_site_key = "0x4AAAAAAEyArHOHfpdNMnDp"
